### PR TITLE
Update Go installation

### PR DESCRIPTION
**Pull request by SuperQ**
* Simplify go version and architecture variables.
* Bumpto Go 1.13.4

### CODE REVIEW

**Comment by derekmarcotte** [comment]
Hey - thanks for the patches.  

I like how it cleans up the playbooks.

I wonder if there's any benefit to keeping the Go version OS dependent for say regressions, or build problems?

**Comment by SuperQ** [comment]
The Go version is now a "default", which means it's still possible to override. For example, you can set it in a role [like this](https://github.com/cloudalchemy/ansible-prometheus/blob/master/defaults/main.yml#L11), but [override it elsewhere](https://github.com/noisebridge/infrastructure/blob/master/group_vars/noisebridge-net/prometheus.yml#L4)

**Comment by SuperQ** [comment]
Updated for Go 1.13.4.

**Comment by derekmarcotte** [comment]
I dunno what happened there, but this is merged.

**Comment by SuperQ** [comment]
lol, github?

**Pull request closed without merging**
